### ISSUE TITLE
Uncaught Error: Call to undefined method Newspack_Newsletters_Active_Campaign::add_contact_with_groups

### ISSUE THREAD

**Issue by mdbitz** [Automattic/newspack-newsletters#1482]
```
PHP Fatal error:  Uncaught Error: Call to undefined method Newspack_Newsletters_Active_Campaign::add_contact_with_groups() in /wordpress/plugins/newspack-newsletters/2.13.1/includes/class-newspack-newsletters-subscription.php:623
Stack trace:
#0 /wordpress/plugins/newspack-newsletters/2.13.1/includes/class-newspack-newsletters-subscription.php(542): Newspack_Newsletters_Subscription::add_contact_to_provider(Array, Array, '')
#1 /wordpress/core/6.4.4/wp-includes/class-wp-hook.php(324): Newspack_Newsletters_Subscription::process_subscription_intents()
#2 /wordpress/core/6.4.4/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /wordpress/core/6.4.4/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#4 /wordpress/core/6.4.4/wp-cron.php(191): do_action_ref_array('newspack_newsle...', Array)
#5 {main}
  thrown in /wordpress/plugins/newspack-newsletters/2.13.1/includes/class-newspack-newsletters-subscription.php on line 623
  ```

With the release of 2.13.1 we are now seeing the above errors in [at-php-errors](https://logstash.a8c.com/logstash/goto/95a66b0c712e9c9c2591d09e5628b1ed).

**Comment by mdbitz** [comment]
Thank you
