### ISSUE TITLE
Updating Failed Errors

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#37]
On occasion I've seen auto-saves of Newsletters fail. The UI shows an `Updating failed.` notification, and this is the error in the log:

```
PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /srv/www/newspack-repos/newspack-newsletters/includes/class-newspack-newsletters-renderer.php:514
Stack trace:
#0 /srv/www/newspack-repos/newspack-newsletters/includes/class-newspack-newsletters.php(506): Newspack_Newsletters_Renderer::render_html_email(Object(WP_Post))
#1 /srv/www/wordpress-simple/public_html/wp-includes/class-wp-hook.php(287): Newspack_Newsletters::sync_with_mailchimp(5227, Object(WP_Post), true)
#2 /srv/www/wordpress-simple/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#3 /srv/www/wordpress-simple/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /srv/www/wordpress-simple/public_html/wp-includes/post.php(4133): do_action('save_post_newsp...', 5227, Object(WP_Post), true)
#5 /srv/www/wordpress-simple/public_html/wp-includes/post.php(4235): wp_insert_post(Array, true)
#6 /srv/www/wordpress-simple/public_html/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(7 in /srv/www/newspack-repos/newspack-newsletters/includes/class-newspack-newsletters-renderer.php on line 514
```

**Comment by jeffersonrabb** [comment]
This is the response from the MJML API:

```
{
    "errors":
    {
        "http_request_failed": ["cURL error 28: Operation timed out after 5000 milliseconds with 60214 out of 87152 bytes received"]
    },
    "error_data": []
}
```

**Comment by jeffersonrabb** [comment]
Probable solution: add a higher timeout parameter to `wp_remote_post()` in https://github.com/Automattic/newspack-newsletters/blob/master/includes/class-newspack-newsletters-renderer.php#L500-L512. The default is 5s, which may be too low for MJML.
