### ISSUE TITLE
MJML API Requests Failing

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#388]
As of today we started seeing all MJML requests fail due to a server certificate issue. This manifests in a few ways in Newspack Newsletters:

- If starting from scratch, when setting the MJML keys in the setup screen, setting them will fail silently. The keys will appear to be saved but you will not advance to template selection and if you view the Settings screen the keys are unset.
- Creating a new Newsletter will cause this fatal: ```Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /srv/www/newspack-repos/newspack-newsletters/includes/class-newspack-newsletters-renderer.php:780 Stack trace: #0 /srv/www/newspack-repos/newspack-newsletters/includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php(381): Newspack_Newsletters_Renderer::render_html_email() #1 /srv/www/newspack-repos/newspack-newsletters/includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php(411): Newspack_Newsletters_Mailchimp->sync() #2 [internal function]: Newspack_Newsletters_Mailchimp->save() #3 /srv/www/wordpress-simple/public_html/wp-includes/class-wp-hook.php(287): call_user_func_array() #4 /srv/www/wordpress-simple/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters() #5 /srv/www/wordpress-simple/public_html/wp-includes/plugin.php(484): WP_Hook->do_action() #6 /srv/www/wordpress-simple/public_html/wp-includes/post.php(4298): do_action() #7 /srv/www/wordpress-simple/public_html/wp-admin/includes/ in /srv/www/newspack-repos/newspack-newsletters/includes/class-newspack-newsletters-renderer.php on line 780```
- For Newsletters that were created previously, saving will fail with `Updating failed.` error message.

The MJML API is returning `{"errors":{"http_request_failed":["cURL error 60: SSL certificate problem: unable to get local issuer certificate"]},"error_data":[]}`

The issue has been raised here: https://github.com/mjmlio/mjml/issues/2114

And https://github.com/Automattic/newspack-newsletters/pull/387 addresses the new Newsletter fatal.

**Comment by jeffersonrabb** [comment]
Resolved here: https://github.com/mjmlio/mjml/issues/2114#issuecomment-747708724
